### ISSUE TITLE
RSMB build fixes on OS X

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto.rsmb#13]
migrated from Bugzilla [#422167](https://bugs.eclipse.org/bugs/show_bug.cgi?id=422167)
status ASSIGNED severity _normal_ in component _RSMB_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[osx-build.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=237591)_ (ID 237591)

On 2013-11-20 11:48:58 -0500, Andy Piper wrote:

> Created attachment 237591
> patches to Broker.c and Socket.c
> 
> Couple of minor defines around some build issues on OS X (specifically 10.9) with deprecated headers etc.

On 2013-11-21 04:31:34 -0500, Jan-Piet Mens wrote:

> On Darwin Kernel Version 12.5.0 I also had to comment out line 284 in Clients.h
> Clients.h:284: error: too many #pragma options align=reset

On 2013-11-21 04:34:39 -0500, Andy Piper wrote:

> (In reply to Jan-Piet Mens from comment # 1)
> 
> > On Darwin Kernel Version 12.5.0 I also had to comment out line 284 in
> > Clients.h
> > Clients.h:284: error: too many #pragma options align=reset
> 
> Interesting, I don't get that error (using the default makefile). I get a bunch of warnings. 10.9 has Darwin kernel 13.0.0.

On 2013-11-24 11:23:05 -0500, Nicholas Humfrey wrote:

> Thanks for the patch Andy :)
> 
> I am also seeing the the same error as Jan-Piet:
> 
> > Clients.h:553: error: too many #pragma options align=reset
> > In file included from Bridge.h:21,
> >                  from Broker.h:23,
> >                  from Broker.c:65:
> 
> Commenting out line 553 (after applying Andy's patch) of Clients.h fixes it.
> 
> OS: Mac OS 10.8.5 (Darwin Kernel Version 12.5.0)
> GCC: gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
> 
> Note that Mac OS X doesn't use gcc anymore by default but the Makefile specifically uses gcc.

On 2014-02-18 10:57:20 -0500, Andy Piper wrote:

> _bump_ any interest in getting this fixed? I just hit the same things on a fresh clone / build.

On 2014-02-18 11:15:00 -0500, Jan-Piet Mens wrote:

> Yes, please! Happened to me a few days ago too. (_sigh_)

On 2014-02-18 16:10:01 -0500, Roger Light wrote:

> Andy, could you modify the patch to combine the two if defines in Broker.c into an if/elif? It makes sense to group them together as they are related. I think the same change needs to go into amqtdd/src/Broker.c as well.
> 
> If you do that you can then either update the patch here, state here that you've complied with the Certificate of Origin and I'll commit the patch, or possibly easier if you do your own commit on a clone on github, following the commit message format as described[1] and point to it here then I'll pull and push.
> 
> I couldn't see the lines mentioned in Clients.h. Any hints?

On 2014-02-26 17:36:59 -0500, Ian Craggs wrote:

> Yes, I want to fix it.  I have to bring out my Mac - I've been busy with the MQTT test material and other stuff...

**Comment by njh** [comment]
Mac OS X compile problems are fixed for me by pull requests #18 and #20

I suggest closing this once those are merged.

**Comment by ralight** [comment]
Pull requests have been accepted so I'm closing this.
