### ISSUE TITLE
How to enable/disable RSMB for MQTT thru web socket

### ISSUE THREAD

**Issue by apanasara** [eclipse/mosquitto.rsmb#30]
How to enable/disable RSMB for MQTT thru web socket? I am trying to implement Eclipse Paho Javascript library but I am not able to connect RSMB [Eclipse Paho mqttws31](https://www.eclipse.org/paho/clients/js/)

**Comment by icraggs** [comment]
Hi.  RSMB does not have support for WebSockets, and I don't maintain it any more.  For WebSocket support you should use Mosquitto.

If you want MQTT-SN support, then you can use the Paho MQTT-SN transparent gateway to connect to Mosquitto.

**Comment by apanasara** [comment]
thanks for prompt clariication
