### ISSUE TITLE
What dose AMQTDD stands for in RSMB?

### ISSUE THREAD

**Issue by apanasara** [eclipse/mosquitto.rsmb#31]
What dose [AMQTDD](https://github.com/eclipse/mosquitto.rsmb/tree/master/amqtdd) stands for in RSMB?

**Comment by icraggs** [comment]
AMQTDD was the name given to RSMB when it was part of the IBM MQ product for a short while.   It stands for MQ Telemetry Daemon for Devices.

**Comment by apanasara** [comment]
thanks for prompt clarification...
