### ISSUE TITLE
Error on make: multiple definition of '...'

### ISSUE THREAD

**Issue by thanosmanolis** [eclipse/mosquitto.rsmb#33]
I don't know if it occurs only for newer gcc versions (I tried it for gcc-9 and gcc-10), but when I tried installing it, the _make_ command outputted 'multiple definition' error for the variables 'Log_levels' and 'bstate'.

The solution that worked for me is doing the following changes in src folder:

- File: **Log.h (line:38)**
Instead of `enum { ... }Log_levels;` ---> `enum Log_levels{ ... };`

- Files: **MQTTSProtocol.c (line:118)**, **Protocol.c (line:44)**, **Users.c (line:36)**
Instead of `BrokerStates* bstate;` ---> `extern BrokerStates* bstate;`

**Comment by ralight** [comment]
Thanks very much, I've fixed that.
