### ISSUE TITLE
Compile for MacOSX 10.8.5

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto.rsmb#5]
migrated from Bugzilla [#456087](https://bugs.eclipse.org/bugs/show_bug.cgi?id=456087)
status UNCONFIRMED severity _enhancement_ in component _RSMB_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

On 2014-12-23 10:38:26 -0500, Laurent Roger wrote:

> In order to compile rsmb in a MacOSX 10.8.5 / XCode 5.1.1, here are the suggested modifications :
> - Makefile, force GCC definition (remove ifndef)
> 
> GCC = gcc -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE
> - Socket.h, add these lines at the end :
> 
> typedef unsigned int u_int;
> typedef unsigned long u_long;
> typedef unsigned char u_char;
> # ifndef IPV6_ADD_MEMBERSHIP
> # define IPV6_ADD_MEMBERSHIP IPV6_JOIN_GROUP
> # define IPV6_DROP_MEMBERSHIP IPV6_LEAVE_GROUP
> # endif
> 
> You can then make and launch :
> ./broker
> 20141223 163728.187 CWNAN9999I Really Small Message Broker
> 20141223 163728.187 CWNAN9998I Part of Project Mosquitto in Eclipse
> (http://projects.eclipse.org/projects/technology.mosquitto)
> 20141223 163728.187 CWNAN0053I Version 1.3.0.2, Dec 23 2014 16:20:11
> 20141223 163728.187 CWNAN0054I Features included: bridge 
> 20141223 163728.187 CWNAN9993I Authors: Ian Craggs (icraggs@uk.ibm.com), Nicholas O'Leary
> 20141223 163728.187 CWNAN0014I MQTT protocol starting, listening on port 1883
> 
> :)

**Comment by njh** [comment]
Mac OS X compile problems are fixed for me by pull requests #18 and #20

I suggest closing this once those are merged.

**Comment by ralight** [comment]
Pull requests are accepted so I'm closing this.
