### ISSUE TITLE
Build warnings on OS X

### ISSUE THREAD

**Issue by ralight** [eclipse/mosquitto.rsmb#9]
migrated from Bugzilla [#428455](https://bugs.eclipse.org/bugs/show_bug.cgi?id=428455)
status ASSIGNED severity _normal_ in component _RSMB_ for _---_
Reported in version _unspecified_ on platform _PC_
Assigned to: Ian Craggs

Original attachment names and IDs:
- _[warning-fixes.diff](https://bugs.eclipse.org/bugs//attachment.cgi?id=243505)_ (ID 243505)

On 2014-02-18 11:17:19 -0500, Andy Piper wrote:

> After applying the patch attached to # 422167 on OS X 10.9, the following warnings remain when the broker is compiled:
> 
> gcc -Wall -s -Os _.c -o broker
> Broker.c:510:34: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
>         sprintf(&ptr[26], ".%.3ld.dmp", ts.tv_usec / 1000);
>                             ~~~~~       ^~~~~~~~~~~~~~~~~
>                             %.3d
> /usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
>   __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
>                                                        ^
> 1 warning generated.
> ld: warning: option -s is obsolete and being ignored
> gcc -Wall -ggdb *.c -o broker_dbg
> Broker.c:510:34: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
>         sprintf(&ptr[26], ".%.3ld.dmp", ts.tv_usec / 1000);
>                             ~~~~~       ^~~~~~~~~~~~~~~~~
>                             %.3d
> /usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
>   __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
>                                                        ^
> 1 warning generated.
> gcc -DMQTTS -Wall -s -Os *.c -o broker_mqtts
> Broker.c:510:34: warning: format specifies type 'long' but the argument has type 'int' [-Wformat]
>         sprintf(&ptr[26], ".%.3ld.dmp", ts.tv_usec / 1000);
>                             ~~~~~       ^~~~~~~~~~~~~~~~~
>                             %.3d
> /usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
>   __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
>                                                        ^
> 1 warning generated.
> MQTTSPacket.c:405:8: warning: unused variable 'enddata' [-Wunused-variable]
>         char_ enddata = &data[header.len - 2];
>               ^
> 1 warning generated.
> ld: warning: option -s is obsolete and being ignored

On 2014-02-26 17:38:37 -0500, Ian Craggs wrote:

> I'll try and get the Mac out soon!

On 2014-05-26 16:54:49 -0400, Nicholas Humfrey wrote:

> Created attachment 243505
> Patch to fix a couple of warnings
> 
> Attached a patch that fixes a couple of the warnings

**Comment by njh** [comment]
These are fixed in Pull Requests #22 and #23

This issue can be closed when those Pull Requests are accepted.

**Comment by ralight** [comment]
Pull requests accepted, thanks.
